language: node_js
node_js:
- '7'
services:
 — docker
before_script:
 — sleep 15
sudo: required
env:
  global:
    DOCKER_EMAIL:
      secure: Oc5ZeqUXf2tv1XzsosGzypTBgg5eunUM5G4qvXyxXHQRtpgIiQE5ng1+KqDANAQyvIBBCC5KBOiNd3AJWy2yRoDqmb/KNoaXfQoQ8BwH5qcZMu6Rf+QF/HidaaW8evGiVp+Ls3JYS7pZE9WpxN0VwwGhTQC34dgI+y3csx7+Mc2XJVB+Smy+aUW+DOF9kQ2PunJhpvJl82+9ZwKoE3tF/LrgLD2dX2wsuLDdPP7YWQi2c5Z1mVYmInViTUp9MglCztabf9dcV2uSCtrimQmyDxhGB0sHZizo+PrZhFZEJWIKPaHD3J+lenvn3l/brLEbAqNYduYDS+vkYOAm2lHtH8jx246TnBBauPntEGHPMwhTinV6uC/++bAy4gMDPPPviTwa25JpieRn4+vT56mA/mgczLRTy4fKJXr4H/8GKIxF/jEG+CWbPAq1y2x4PxLP8WHAO0tLWSN0RSW62WYF6GjGPp+1eXMklNmfI2P9G64WU1fmtZgde55OK/JsNKrRktPi+4skYBpMUL7B4/6i70Jr4QszX5N+x8Qs4aufUpMrRZZLw3Ej3LCE7vlhzL+EjpUEK2lGjDbpcMu3bCR1VAGbl42d7J8mxnxLXrGKk5T6T9WcVsumrOzOGWG0Hg8VKliVWh7knOvTwYBNxvBp0CdrJmENZnqoEVNxxzDx2J8=
    DOCKER_PASS:
      secure: p9grLdiGI/LnxJZ55Y1czzFmaQ0tOyzMocob0n2X6mF7eFXeNrFhSIaTDwbQVsKfXmvfpKpESse+PsEJrN7TPOdlkfi1YrDLpDOt3G5p6r8ZLQfExALE52p5B8LnYKdGE6GCCfKjYA6VBpXeQh6SR2zPKvZZ1m7mPhLI+lfCVMlQ3h9w9XeayufKP9yS4GhYDdDN5equcHLKFKaw8tcbCVd3HSBXDBfL3Sy54LLul82fNp6QnTZbhxk5/P280orfHrnl/BUSZ9qI1Ftm1KEI/dnSuzBoD4S4i9eutgo70DQvith4dE71b2VJqN7PI6htLUN8FqfQU4A+Lk357CDl6riDGE+Dxy4LPG5T5gLslxZVVLuGM1atvFZGp9CfbRkzDCbhdNTfbEYSAKaiqmkR7nSL/C+IEOy6lW67HJG60Clghzuj3rkKerw4Wnguiqr/0CCeTDbDol47WvnllnvS7FG96ue9OWnVQEYA0uUP/mDqA2qFh9WWqQcQcHtu9FOQw2t4yPU3OSE+WeDVWkz97aMGs1x1T6+pYxdJlN9mzdwcjkvnhEwYreIU4XOYFteiYtZCNXjZE32oMnKugR9fWlfRZTCW38DYTJxAEUltPhNrpMZoqbtZUgnwleyynK4rtcB7PNlNeWu6QV52fy+B4TB6nBYZCdJ4/feSRj2OvTY=
    DOCKER_USER:
      secure: Y4Hs3gl28YwI7Inh0FXKN00eFjKFOKb2j+/IP+a7rR7bV9YdTQ/SY1RaKu3RL8IMLTtmGe2oliF6QD1BaprCZ6EUJxgUdpcMvP5Gce+fa+RoBQSdRZMOtv5Cv6qTRqlHkWZhdUWjnb+Q7THalz2qQhyUSE0EoF/xUEudl+WRx6GZGQIS0ss35LRC5LW9wJvYriFrClks0tYUjVPhZuHgOO6FqYIzkxjEUX0cZeFcS4tV2K+4SEMZFrud8ww246GrpscOFHqEXmBPbdUxHWVj3NlGXi9ehDuv2rXBrEJlrTPZVU6cVGg+j5sxhflK1yiaVrPxqpFLYxSI5NAOy1ti7QpczdfUcVKIoQaPvhhbPCen9Pn6jzGc1aYQ7Qnqv7KoYSoxKNFSrTVyA3DKQVz0zPVM/iamaZlI0sCZ6q+2tNFzAgmmdXkJHUauBq7anehfbMCrEHIggnoTVxYLCGewLvUjiLbZk3blcScyRCsAwGcgEcUV1YKSck0N1nOhsdrSugtQsaNyAtjbei/+AqwlFJJ3P+UpoXpa17Y2mfiVGGWCEk+b1S1ANILIx3Xgj2Wo1witErrs8m9PMSJdNDM5DrZHdzwYpzmdzXf9fWebHvERwCuDhc053EgYVOrwBmaYhP+dPqyhfQyejCPj5HGS3hk93Q/I/Vt6LEtP32iXcXE=
  — COMMIT=${TRAVIS_COMMIT::6}
after_success:
 — docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
 — export REPO=$DOCKER_USER/mosesy
 — export TAG='if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi'
 — echo $REPO:$TAG:$COMMIT
 — docker build -f Dockerfile -t $REPO:$COMMIT .
 — docker tag $REPO:$COMMIT $REPO:$TAG
 — docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
 — docker push $REPO
