language: node_js
node_js:
- '7'
services:
 - docker
sudo: required
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
before_script:
  - chmod +x ./deploy.sh
  - ./deploy.sh
after_success:
  - chmod +x ./pushECS.sh
  - ./pushECS.sh
