language: node_js
node_js:
- '7'
services:
 - docker
sudo: required
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
before_script:
   - chmod +x ./deploy.sh
after_success:
  - ./deploy.sh
  #- ./pushECS.sh
